### ISSUE TITLE
Want to know the algorithm of AEC and DTD

### ISSUE THREAD

**Issue by rick2003-gh** [athena-team/athena-signal#20]
Hi dear athena developer,
I'm a junior leaner of audio-processing, and I want to learn AEC related knowledges, could you tell me the algorithm of AEC and DTD that athena-signal used? What's papers that I can refer to？

**Comment by songhui5561** [comment]
we use the same algorithm as Webtrc-DTD, so you can find details in Webrtc website.

AEC is composed of linear echo cancellation(LEC) and residual echo suppression (RES). LEC is NLMS-based adaptive filtering algorithm, and RES is extracted from Speex-AEC.

**Comment by rick2003-gh** [comment]
Hi @songhui5561 :
        Thanks for your helpgul reply ^ ^
        Did you mean this webrtc website : **https://bugs.chromium.org/p/webrtc/issues/list** ? I have searched webrtc-dtd related information in this website but didn't see anything about Webtrc-DTD. Could you tell me the website ? Thanks a lot!

**Comment by songhui5561** [comment]
https://topic.alibabacloud.com/a/an-introduction-to-webrtcs-echo-cancellation-aec-aecm-algorithm_8_8_10267058.html

[Bastiaan.pdf](https://github.com/athena-team/athena-signal/files/5768423/Bastiaan.pdf)

**Comment by songhui5561** [comment]
Oh I misread your question. I thought you meant TDE ... ...

We use ERLE for DTD in linear echo cancellation, and RES output signal to update DTD overall. Maybe you can find information about ERLE and RES (which is also called 'NLP' in webrtc) first.

**Comment by rick2003-gh** [comment]
Hi @songhui5561 :
I download the latest version of athena-signal, and replace example's  input_file, ref_file and output_file with wavs to do AEC. 

[https://drive.google.com/file/d/1jWq8TOTaNMOHTOPIp7QVrFXgjm2qyJ3q/view?usp=sharing](url)

Belows are informations of those wavs :
far16K.pcm   : 30 secs far-side human sound
mic16K.pcm  : 30 secs recording, containing far-side talk and double talk
        *Farside-talk : 0 ~ 7.5 secs and 22.5 ~ 30.0 secs 
        *Double-talk  : 7.5 ~ 22.5 secs
near.wav : 30 secs near-side human sound

**Question : I found that AEC result of 22.5 ~ 30.0 secs (far-side talk) are not good enough (still have some echo), could you tell me how to improve the AEC performance?**

**Comment by songhui5561** [comment]
here is my advice: 
1. you can set 'commutation mode', rather than 'recognition mode'.  Some parameters are set to different value in different modes, so you can track these parameters, and tune them.
2. check if DTD result is right. We use the 1-stage RES, and the output of LEC, to update DTD. So you can check DTD after the first stage RES.

**Comment by songhui5561** [comment]
here is my advice:

you can set 'communication mode', rather than 'recognition mode'. Some parameters are set to different value in different modes, so you can track these parameters, and tune them.
check if DTD result is right. We use the 1-stage RES, and the output of LEC, to update DTD. So you can check DTD after the first stage RES.
